"""
CONFIG FILE
config file with hardware specifications
"""

# PROPERTIES

numSegments: 2
servoPins: {
    1: {
        "lr": 12,
        "bf": 32
    },
    2: {
        "lr": 33,
        "bf": 35
    }  
}