numSegments: 1
servoPins: {
    0: {
        "central": 0,
    },
    1: {
        "lr": 0,
        "ud": 1
    },
    2: {
        "lr": 2,
        "ud": 3
    },
    3: {
        "lr": 4,
        "ud": 5
    }
}
