servoPins:
  {
    0: { "central": 6 },
    1: { "lr": 0, "ud": 1 },
    2: { "lr": 2, "ud": 3 },
    3: { "lr": 4, "ud": 5 },
  }

calibrationDict:
  {
    "central":
      { "servoIdx": 0, "minAngle": 0, "maxAngle": 270, "angleInterval": 10 },
    "seg1":
      {
        "servoIdx": 1,
        "minAngle": { lr: 90, ud: 90 },
        "maxAngle": { lr: 180, ud: 180 },
        "angleInterval": 20,
      },
    "seg2":
      {
        "servoIdx": 2,
        "minAngle": { lr: 90, ud: 90 },
        "maxAngle": { lr: 180, ud: 180 },
        "angleInterval": 20,
      },
    "seg3": { "servoIdx": 3 },
  }
