numSegments: 3
servoPins: {
    0: {
        "central": 0,
    },
    1: {
        "lr": 0,
        "bf": 1
    },
    2: {
        "lr": 2,
        "bf": 3
    },
    3: {
        "lr": 4,
        "bf": 5
    }  
}

numSegmentsToCalib: 2
calibrationDict: {
    1: {
        "minAngle": 0,
        "maxAngle": 180,
        "angleInterval": 30
    },
    2: {
        "minAngle": 0,
        "maxAngle": 180,
        "angleInterval": 30
    }
}